title: ML4GW+Controls Workshop @ LVK
description: 1-day Workshop on Machine Learning for Gravitational-Wave data analysis and controls.
baseurl: "/iucaa-workshop-2026"
url: "https://ml4gw.github.io"
theme-dark: false
exclude:
  - vendor
  - .bundle
  - Gemfile
  - Gemfile.lock

